### ISSUE TITLE
Leukocytes / Lymphocytes

### ISSUE THREAD

**Issue by GlastonburyC** [dakomura/SegPath_code#4]
In your dataset you have stained for both Leukocytes and Lymphocytes. Does this mean that the Lymphocyte class is just a subset of the Leukocytes class? Is it possible using the SegPath data to have mutually exclusive classes? Thanks!

**Comment by dakomura** [comment]
Hi,
- CD3/CD20 are expressed in lymphocytes, whereas CD45 is expressed in all leukocytes, including lymphocytes. This indicates that the lymphocyte class is a subset of the leukocyte class.
- Since lymphocytes and leukocytes were stained separately, it's impossible to create a dataset for mutually exclusive classes directly. To address this issue, we first predicted leukocytes and then overwrote these predictions with lymphocyte predictions to achieve mutually exclusive predictions, as described in "Multi-cell-type segmentation" section in the Experimental Procedures.

**Comment by GlastonburyC** [comment]
Ok great. So I could predict for each leukocyte whether it's a lymphocyte, plasma cell or myeloid cell, and reclassify accordingly.

**Comment by dakomura** [comment]
Yes.
